# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='first_question',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Erste Frage'),
        ),
        migrations.AlterField(
            model_name='info',
            name='first_text',
            field=models.CharField(default=None, max_length=600, null=True, verbose_name='Erster Text'),
        ),
        migrations.AlterField(
            model_name='info',
            name='media',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Medien-Anhang'),
        ),
        migrations.AlterField(
            model_name='info',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Veröffentlicht am'),
        ),
        migrations.AlterField(
            model_name='info',
            name='second_question',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Zweite Frage'),
        ),
        migrations.AlterField(
            model_name='info',
            name='second_text',
            field=models.CharField(default=None, max_length=600, null=True, verbose_name='Zweiter Text'),
        ),
    ]
