# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170321_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='User ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hinzugefügt am')),
            ],
            options={
                'verbose_name': 'Facebook User',
                'verbose_name_plural': 'Facebook User',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Infos'},
        ),
        migrations.AlterField(
            model_name='info',
            name='first_question',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Erste Frage'),
        ),
        migrations.AlterField(
            model_name='info',
            name='first_text',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Erster Text'),
        ),
        migrations.AlterField(
            model_name='info',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang'),
        ),
        migrations.AlterField(
            model_name='info',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veröffentlicht am'),
        ),
        migrations.AlterField(
            model_name='info',
            name='second_question',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zweite Frage'),
        ),
        migrations.AlterField(
            model_name='info',
            name='second_text',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Zweiter Text'),
        ),
    ]
