# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170522_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(help_text='Der Eingabetext des Nutzers', max_length=128, unique=True, verbose_name='Eingabe')),
                ('output', models.CharField(help_text='Die Antwort, die der Bot auf die Eingabe geben soll', max_length=640, verbose_name='Antwort')),
            ],
            options={
                'verbose_name_plural': 'Dialog-Schnipsel',
                'verbose_name': 'Dialog-Schnipsel',
            },
        ),
    ]
