# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='first_attachment_id',
            field=models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
        migrations.AddField(
            model_name='info',
            name='intro_attachment_id',
            field=models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
        migrations.AddField(
            model_name='info',
            name='second_attachment_id',
            field=models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
    ]
