# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170523_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='breaking',
            field=models.BooleanField(default=False, help_text='Breaking-News werden außerhalb der regelmäßigen Push-Zyklen zu der angegebenen Zeit gesendet', verbose_name='Breaking?'),
        ),
        migrations.AddField(
            model_name='info',
            name='first_media_note',
            field=models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AddField(
            model_name='info',
            name='intro_media_note',
            field=models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AddField(
            model_name='info',
            name='second_media_note',
            field=models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung'),
        ),
    ]
