# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20170523_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='third_attachment_id',
            field=models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
        migrations.AddField(
            model_name='info',
            name='third_media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dritter Medien-Anhang'),
        ),
        migrations.AddField(
            model_name='info',
            name='third_media_note',
            field=models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AddField(
            model_name='info',
            name='third_question',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dritte Frage'),
        ),
        migrations.AddField(
            model_name='info',
            name='third_text',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Dritter Text'),
        ),
    ]
